name: colorbox
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dotted_line: ^3.1.0
  double_back_to_close_app: ^2.1.0
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  flutter_svg: 0.23.0+1
  flutter_zoom_drawer: ^2.3.1+1
  get: 4.6.1
  getwidget: ^2.0.4
  graphql: ^5.0.1
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  lottie: ^1.4.1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  url_launcher: ^6.1.5
  video_player: ^2.4.7
  webview_flutter: ^2.0.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icon/
    - assets/icon/orders/
    - assets/videos/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_Regular.ttf
        - asset: assets/fonts/Inter_Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_Light.ttf
          weight: 300
